language: python
sudo: false

cache:
  directories:
    - "~/.cache/pip"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libfreetype6-dev
      - libatlas-base-dev
      - libatlas3-base
      - gfortran

python:
  - 2.7

install:
  - pip install pip setuptools wheel --upgrade
  - pip install -e .
